### ISSUE TITLE
Solver fails sometimes but not others for a single configuration

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box-interactive-api#413]
Running the attached configuration sometimes returns a "Solver failed" error, but sometimes runs to completion.
[config_0715_C5_MBO.zip](https://github.com/user-attachments/files/16273133/config_0715_C5_MBO.zip)

**Acceptance Criteria**
- Multiple runs (10+) of the attached configuration returns consistent results.

**Ideas**
- See if this problem persists after switching to Python-based MusicBox (#400)
- Try running this configuration with the Python-based MusicBox directly multiple times
- Investigate whether the re-use of folders named with the session id is related to this bug
- This may have been fixed as part of the switch to the python-based MusicBox, but should be tested

**Comment by K20shores** [comment]
The attached configuraiton isn't correct for the new version of music box since micm is more strict about the keys it allows, but after correcting the configuraiton (`note` becomes `__note`, `music_box_type` becomes `__music_box_type`, `species` becomes `__species` `scaling_factor` becomes `scaling factor`), I was able to run the configuration 50 times in a row without a failure. I'm assuming whatever was wrong is not an issue with micm
